# 博客网站主页语言、个人信息的设置
languageCode = "zh-cn"
languageName = "Chinese"
weight = 1

title = "柒修远的个人博客"

[params]
  displayName = "CN"
  isoCode = "zh-cn"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/GeNie.png"
  # description = "柒修远的个人博客"
  # copyright = "Copyright © 2023 柒修远的个人博客. All Rights Reserved. Powered by Hugo & Blowfish.  "
  

[author]
name = "柒修远"
image = "img/Gaine.JPG"
# headline = "路漫漫其修远兮，吾将上下而求索。"
bio = "正在不断学习的研究僧"
links = [
{ email = "mailto:wenchangkeh@gmail.com" },
  { github = "https://github.com/QiXiuYuano" },
  { twitter = "https://twitter.com/QiXiuYuano" },
  { telegram = "https://t.me/QiXiuYuan" },
  
  #     { link = "https://link-to-some-website.com/" },
  #     { apple = "https://www.apple.com" },
  #     { gitlab = "https://gitlab.com/username" },
  #     { google = "https://www.google.com/" },
  #     { instagram = "https://instagram.com/username" },
  #     { reddit = "https://reddit.com/user/username" },
  #     { youtube = "https://youtube.com/username" },
  ]