# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

[highlight]
  
  noClasses = false

  anchorLineNos = false
  codeFences = true
  guessSyntax = true
  hl_Lines = ''
  hl_inline = false
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  # style = 'darcula'
  # tabWidth = 4

  # codeFences：代码围栏功能，这个功能一般都要设为 true 的，不然很难看，就是干巴巴的-代码文字，没有颜色。
  # guessSyntax：猜测语法，这个功能建议设置为 true, 如果你没有设置要显示的语言则会自动匹配。
  # hl_Lines：高亮的行号，一般这个不设置，因为每个代码块我们可能希望让高亮的地方不一样。
  # lineNoStart：行号从编号几开始，一般从 1 开始。
  # lineNos：是否显示行号，我比较喜欢显示，所以我设置的为 true.
  # lineNumbersInTable：使用表来格式化行号和代码,而不是 标签。这个属性一般设置为 true.
  # noClasses：使用 class 标签，而不是内嵌的内联样式


[tableOfContents]
  startLevel = 2
  endLevel = 4
