# -- Theme Options --
# These options control how the theme functions and allow you to
# customise the display of your website.
#
# Refer to the theme docs for more details about each of these parameters.
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"  # blowfish
defaultAppearance = "light" # valid options: light or dark
autoSwitchAppearance = true # 是否根据访问者的操作系统偏好自动切换

enableSearch = true # 是否启用站点搜索
enableCodeCopy = true # 是否为块启用复制到剪贴板按钮

mainSections = ["posts"]
# robots = ""


# disableImageZoom = false # 禁用站点中所有图像的图像缩放功能
# disableImageOptimization = true # 禁用网站中所有图像的图像调整大小和优化功能
# defaultBackgroundImage = "/img/backgroud.png" # background主页布局默认背景图像
# defaultFeaturedImage = "/img/ocean.jpg" # 文章中所有图像的默认背景图像

highlightCurrentMenuArea = true # 菜单选中后有标志
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed" # valid options: basic, fixed, fixed-fill, fixed-fill-blur

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true   # 是否在页脚展示 Power by
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile" # valid options: page, profile, hero, card, background, custom
  showRecent = true
  showRecentItems = 5
  showMoreLink = true
  showMoreLinkDest = "/posts"
  cardView = false
  cardViewScreenWidth = false
  layoutBackgroundBlur = false


[article]
  showDate = true
  showDateUpdated = false
  #showViews = true
  #showLikes = true
  showHero = true
  heroStyle = "basic" # valid options: basic, big, background
  layoutBackgroundBlur = true # heroStyle为background时,背景图片随着滚动变得模糊
  layoutBackgroundHeaderSpace = false # heroStyle为background时,在标题和正文之间添加空间
  showBreadcrumbs = true  # 多层目录嵌套时是否显示多级目录
  showDraftLabel = true

  showEdit = false
  # editURL = "https://github.com/username/repo/"
  editAppendPath = false

  seriesOpened = true
  showHeadingAnchors = true # 标题锚链接是否显示在文章内的标题旁边
  showPagination = true
  invertPagination = false
  showReadingTime = true
  showTableOfContents = true  # 文章目录
  showTaxonomies = true
 
  showAuthor = true
  showAuthorsBadges = true
  showWordCount = true
  showSummary = true
  showComments = true
  sharingLinks = [ "email",  "twitter", "telegram"]


[list]
  # showHero = true
  # heroStyle = "background"
  showBreadcrumbs = true
  layoutBackgroundHeaderSpace = true # only used when heroStyle equals background
  showSummary = true
  showTableOfContents = false
  showCards = true  # 每篇文章是否显示为卡片或简单的内嵌文本
  groupByYear = true  # 列表页面上的文章是否按年份分组


[sitemap]
  excludedKinds = []

[taxonomy]    # 配置有关分类（categories）和标签（tags）的设置
  showTermCount = true  # 显示分类或标签中每个元素的次数
  # cardView = true

[term]
  # showHero = false
  # # heroStyle = "background" # valid options: basic, big, background, thumbAndBackground
  # showBreadcrumbs = false
  # showViews = false
  # showLikes = false
  # showTableOfContents = true
  # groupByYear = false
  # cardView = false
  # cardViewScreenWidth = false
  

[fathomAnalytics]
  # site = "ABC12345"
  # domain = "llama.yoursite.com"

[buymeacoffee]
  # identifier = "nunocoracao"
  # globalWidget = true
  # globalWidgetMessage = ""
  # globalWidgetColor = "#FFDD00"
  # globalWidgetPosition = "Right"

[verification]
  # google = ""
  # bing = ""
  # pinterest = ""
  # yandex = ""
